name: Development workflow

on:
  push:
    branches:
      - develop

# Here the environment variable is declared in workflow level
env:
  # Replace with your Orchestrator Values 
  PROJECT_NAME: uipath.github.action                         
  PROJECT_FOLDER: ${{ github.action_path }}
  ORCH_URL: https://cloud.uipath.com/RPABOTSWORLD/DEV
  ORCH_TENANT: ${{ secrets.UIPATHTENANTNAME }}
  ORCH_CLIENT_ID: ${{ secrets.UIPATHCLIENTID }}
  ORCH_USER_KEY: ${{ secrets.UIPATHUSERKEY }}
  ORCH_ACC_NAME: ${{ secrets.UIPATHACCOUNTNAME }}
