# .github/workflows/main-workflow.yml
name: Main Workflow

on:
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      some_input: "static value"  # Some input specific to the reusable workflow
    secrets:
      SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}  # Passing the secret
    env:
      COMBINED_VAR: "Hello-${{ secrets.SECRET_TOKEN }}"  # Combine string and secret
