# .github/workflows/reusable-workflow.yml
name: Reusable Workflow

on:
  workflow_call:
    inputs:
      some_input:
        required: true
        type: string
    secrets:
      SECRET_TOKEN:
        required: true

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Print combined variable
        run: |
          echo "The combined value is $COMBINED_VAR"
          # You can now use $COMBINED_VAR in other steps as well
