name: Scheduled Workflow

on:
  schedule:
    - cron: '* * * * *' # This will trigger the workflow at midnight every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Add your workflow steps here
