name: Determine Trigger Type

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Example schedule: run daily at midnight UTC

jobs:
  determine_trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Check if workflow is manually triggered
        id: manual_trigger
        run: |
          if ($env:GITHUB_EVENT_NAME -eq 'workflow_dispatch') {
            Write-Output "Manual"
          }
          else {
            Write-Output "Scheduled"
          }

      - name: Set Trigger Type
        run: echo "TriggerType=${{ steps.manual_trigger.outputs.result }}" >> $GITHUB_ENV

      - name: Display Trigger Type
        run: |
          $triggerType = $env:TRIGGER_TYPE
          Write-Output "Trigger type is $triggerType"
        env:
          TRIGGER_TYPE: ${{ env.TriggerType }}
