name: Scheduled Workflow

on:
  schedule:
    - cron: '* * * * *' # This will trigger the workflow at midnight every day

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Secret
        run: echo "My secret is ${{ secrets.SCOPE }}"

      # Add your workflow steps here
