# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# Here the environment variable is declared in workflow level
env:
  # Replace with your Orchestrator Values 
  PROJECT_NAME: uipath.github.action                         
  PROJECT_FOLDER: ${{ github.action_path }}
  ORCH_URL: "https://hpsilt435.hpillc.local:444"
  ORCH_TENANT: "Default"
  ORCH_applicationId: "2183c503-bc6e-479f-aa90-842d8d7b5ebe"
  ORCH_applicationSecret: "5R4sViy^ZzVVzdsD"
  ORCH_applicationScope : ${{vars.SCOPE}}

jobs:
  print-details:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install js-yaml

    - name: Generate HTML
      run: node generateHTML.js

    - name: Upload HTML artifact
      uses: actions/upload-artifact@v2
      with:
        name: html-output
        path: output.html
