name: Test, Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
      
jobs:
  StartTime:
    runs-on: [self-hosted, windows]
    steps:
      - name: Assign Environment Variables
        shell: pwsh
        run: |
          $env:CURRENT_TIME = (Get-Date -Format 'yyyy-MM-ddTHH:mm:sszzz')
          Write-Output "Assigning values to environment variables"
          Write-Output "CURRENT_TIME: $env:CURRENT_TIME"  # Debug statement
          
      - name: Display Current Time
        shell: pwsh
        run: |
          Write-Output "Current Time: $env:CURRENT_TIME"
