name: Test, Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
      
jobs:
  StartTime:
    runs-on: [self-hosted, windows]
    steps:
      - name: Set current time to a variable
        id: set_time
        run: |
          $currentTime = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
          Write-Host "::save-state name=current_time::$currentTime"

      - name: Display current time
        run: echo "Current time is ${{ steps.set_time.outputs.current_time }}"

      - name: Use current time in another step
        run: echo "The current time is ${{ steps.set_time.outputs.current_time }}"
