name: Determine Trigger Type

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Example schedule: run daily at midnight UTC

jobs:
  determine_trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Set Trigger Type
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Manual" >> $GITHUB_ENV
          else
            echo "Scheduled" >> $GITHUB_ENV
          fi
      - name: Display Trigger Type
        run: echo "Trigger type is ${{ env.TRIGGER_TYPE }}"
        env:
          TRIGGER_TYPE: ${{ env.TRIGGER_TYPE }}
