name: Test, Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
      


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up environment variable
      run: echo "MY_VAR=mystring-${{ secrets.Pwd }}" >> $GITHUB_ENV

    - name: Use environment variable
      run: echo "The value of MY_VAR is $MY_VAR"
      env:
        MY_VAR: ${{ env.MY_VAR }}
