name: Test, Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
      
jobs:
  StartTime:
    runs-on: [self-hosted, windows]
    outputs:
      current_time: ${{ steps.set_time.outputs.current_time }}
    steps:
      - name: Set current time to a variable
        id: set_time
        run: |
          $currentTime = Get-Date -Format "yyyy-MM-ddTHH:mm:sszzz"
          Write-Output $currentTime

  Print:
    needs: StartTime
    runs-on: [self-hosted, windows]
    steps:
      - name: Use current time in another job
        run: |
          currentTime="${{ needs.StartTime.outputs.current_time }}"
          echo "The current time is $currentTime"
