name: Test, Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
      
jobs:
  build_and_push:
    name: Build and Push
    runs-on: [self-hosted, windows]
    steps:
    - name: Determine version
      shell: pwsh
      run: |
        TERMINUS_RELEASE=Get-Date -Format "yyyy-MM-ddTHH:mm:sszzz"
        echo "TERMINUS_RELEASE=$TERMINUS_RELEASE" >> $GITHUB_ENV

    - name: Install Terminus
      shell: pwsh
      run: |
        
            env:
              TERMINUS_RELEASE: ${{ inputs.CURRENT_TIME || env.TERMINUS_RELEASE }}
