name: Test, Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
      
jobs:
  build_and_push:
    name: Build and Push
    runs-on: [self-hosted, windows]
    steps:
    - name: Determine version
      shell: pwsh
      run: |
        $TERMINUS_RELEASE = Get-Date -Format "yyyy-MM-ddTHH:mm:sszzz"
        $env:TERMINUS_RELEASE = "$TERMINUS_RELEASE"

    - name: Install Terminus
      shell: pwsh
      run: |
            $TERMINUS_RELEASE = $env:TERMINUS_RELEASE
            Write-Output "$TERMINUS_RELEASE"
