name: Test, Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master
      
jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
    - name: Determine version
      shell: bash
      run: |
        TERMINUS_RELEASE=5
        echo "TERMINUS_RELEASE=$TERMINUS_RELEASE" >> $GITHUB_ENV

    - name: Install Terminus
      shell: bash
      run: |
        
            env:
              TERMINUS_RELEASE: ${{env.TERMINUS_RELEASE }}
              echo "time $env.TERMINUS_RELEASE"
