name: Scheduled Workflow

on:
  workflow_dispatch:

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Secret
        run: echo ${{ vars.SCOPE }}

      # Add your workflow steps here
