name: Determine Trigger Type

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Example schedule: run daily at midnight UTC

jobs:
  determine_trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Check if workflow is manually triggered
        if: github.event_name == 'workflow_dispatch'
          echo $github.event_name
        run: echo "Manual" >> $GITHUB_ENV

      - name: Check if workflow is scheduled
        if: github.event_name != 'workflow_dispatch'
        run: echo "Scheduled" >> $GITHUB_ENV

      - name: Display Trigger Type
        run: echo "Trigger type is $TRIGGER_TYPE"
        env:
          TRIGGER_TYPE: ${{ env.TRIGGER_TYPE }}
