name: Determine Trigger Type

on:
  push:
    branches:
      - main
  schedule:
  - cron: '*/1 * * * *' # Example schedule: run daily at midnight UTC

jobs:
  determine_trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Check if workflow is manually triggered
        id: manual_trigger
        if: github.event_name == 'workflow_dispatch'
        run: echo "Manual"
      
      - name: Check if workflow is scheduled
        id: scheduled_trigger
        if: github.event_name != 'workflow_dispatch'
        run: echo "Scheduled"

      - name: Set Trigger Type
        run: |
          if ($env:manual_trigger) {
            echo "TriggerType=Manual" >> $GITHUB_ENV
          }
          else {
            echo "TriggerType=Scheduled" >> $GITHUB_ENV
          }

      - name: Display Trigger Type
        run: |
          $triggerType = $env:TRIGGER_TYPE
          Write-Output "Trigger type is $triggerType"
        env:
          TRIGGER_TYPE: ${{ env.TriggerType }}
